# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: r-base
#image: reetututeja/seurat:3.1
# image: continuumio/miniconda3
image: davidliwei/seurat-mageck:0.5.9.2


options:
  docker: true

pipelines:
  default:
    - step:
        script: # build up the pipeline
          # install dependencies
          # - apt-get update
          # - apt-get install -y libssl-dev libcurl4-openssl-dev
          # - R --vanilla -e 'install.packages(c("BiocManager"), repos="https://cloud.r-project.org")'
          # - R --vanilla -e 'BiocManager::install("multtest")'
          # - R --vanilla -e 'install.packages(c("Seurat","knitr"), repos="https://cloud.r-project.org")'
          - R --vanilla -e 'library(reticulate);use_python("/usr/local/bin/python");py_config()'
          # generate package 
          - R CMD build bioconductor
          - ls -la
          - R CMD INSTALL scMAGeCK*.gz
          # Test the demo
          - cd demo/demo1*
          - bash run_scmageck_lr_v3.sh
          - bash run_scmageck_rra_v3.sh
          - cd ../demo3_GSEA
          - Rscript lr_gsea_demo.R
          - Rscript rra_gsea_demo.R
    - step:
        script: # build Docker image 
          - export IMAGE_NAME=davidliwei/scmageck:latest
          - docker build -t $IMAGE_NAME .
          # authenticate with Docker Hub
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
