# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: r-base
#image: reetututeja/seurat:3.1
# image: continuumio/miniconda3

pipelines:
  default:
    - step:
        script: # build up the pipeline
          # install dependencies
          - apt-get update
          - apt-get install -y libssl-dev libcurl4-openssl-dev
          - R --vanilla -e 'install.packages(c("BiocManager"), repos="https://cloud.r-project.org")'
          - R --vanilla -e 'BiocManager::install("multtest")'
          - R --vanilla -e 'install.packages(c("Seurat","knitr"), repos="https://cloud.r-project.org")'
          # - conda install -c bioconda r-seurat 
          # generate package 
          - R CMD build bioconductor
          - ls -la
